version: '3.3'
services:
    web:
        build:
            context: ./
            dockerfile: DockerFile
        ports:
            - '8081:80'
        volumes:
            - '../Site:/var/www/html'
        links: 
            - mysql
        container_name: web
    mysql:
        image: 'mysql:latest'
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=scoutdemo
        volumes:
            - '../MySqlSetupScripts:/docker-entrypoint-initdb.d'